; comment 1
# comment 2

book.title: Go Generics 101
book.author: Tapir Liu

; optional
; Recommanded ration: 1 : 1.6
; Recommanded sizes: 1000x1600, 1600x2560
book.cover-image: res/cover-1000x.png

; optional.
; will be shadowed by the cli argument.
; blank means to retrieve from git repo.
book.version: 

cover-text.version: -= {{.Version}}-{{.ReleaseDate}} =-
; x anchor: left | center | right
cover-text.version.center: 500
; y anchor: top | middle | bottom
cover-text.version.middle: 328
; in pixels (? to confirm)
cover-text.version.font-size: 29
; hex, default: #000
cover-text.version.color: #000





