name: Main

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  main:
    name: Main Process
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      # https://github.com/golangci/misspell/tree/master#readme
      - name: Install misspell
        run: |
          go install github.com/golangci/misspell/cmd/misspell@latest
          misspell -v

      - name: Run misspell
        run: |
          misspell pages
